def getRequirementsOfBasicToolsI() -> tuple[int, int, int]:
    COST_OF_BASIC_TOOLS_I = 400
    REQUIRED_IRON_FOR_BASIC_TOOLS_I = 50
    REQUIRED_STONE_FOR_BASIC_TOOLS_I = 200
    return (COST_OF_BASIC_TOOLS_I, REQUIRED_IRON_FOR_BASIC_TOOLS_I, REQUIRED_STONE_FOR_BASIC_TOOLS_I)